# Generated by Django 6.0 on 2026-01-08 14:01

import core.models.auxiliares
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_contato_demanda_descricao_demanda_observacao_and_more'), ('core', '0003_demanda_data_fechamento'), ('core', '0004_pendencia'), ('core', '0005_historicalpendencia'), ('core', '0006_historicaldemanda'), ('core', '0007_situacao_padrao'), ('core', '0008_situacao_pendente'), ('core', '0009_demanda_anexos_historicaldemanda_anexos'), ('core', '0010_documento_remove_demanda_anexos_and_more'), ('core', '0011_delete_documento_alter_anexodemanda_options_and_more'), ('core', '0012_alter_situacao_cor_hex_alter_situacao_padrao_and_more'), ('core', '0013_alter_anexodemanda_options_alter_demanda_descricao_and_more'), ('core', '0014_pendencia_resolvido_por'), ('core', '0015_alter_situacao_options_remove_demanda_nivel_and_more'), ('core', '0016_resultadosesperados_riscos_and_more'), ('core', '0017_alter_demanda_atualizado_em_alter_demanda_criado_em_and_more'), ('core', '0018_rename_titulo_tarefas_nome'), ('core', '0019_rotulos_alter_demanda_options_and_more'), ('core', '0020_alter_historicaldemanda_options_and_more'), ('core', '0021_tarefas_concluido_em_alter_tarefas_atualizado_em_and_more'), ('core', '0022_tarefas_resolvida_alter_demanda_situacao_and_more'), ('core', '0023_tarefas_pendencia_resolvida_em_and_more'), ('core', '0024_historicaltarefas')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor_hex', models.CharField(default='#6c757d', help_text='Ex: #d9534f', max_length=7)),
                ('proximas_situacoes', models.ManyToManyField(blank=True, to='core.situacao', verbose_name='Buckets seguintes')),
                ('padrao', models.BooleanField(default=False, help_text='Bucket padrão para novas demandas', verbose_name='Padrão')),
                ('pendente', models.BooleanField(default=False, help_text="Representa estado 'pendente'")),
            ],
            options={
                'verbose_name_plural': 'Buckets',
                'verbose_name': 'Bucket',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_prazo', models.DateField(blank=True, null=True, verbose_name='Data de Prazo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subitens', to='core.demanda', verbose_name='Demanda Pai')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao', verbose_name='Situação')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoatividade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('solicitantes', models.ManyToManyField(blank=True, related_name='demandas_solicitadas', to='core.contato')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dependencias_externas', models.TextField(blank=True, verbose_name='Dependencias Externas')),
                ('objetivo_geral', models.TextField(blank=True, verbose_name='Objetivo Geral')),
                ('porcentagem_concluida', models.PositiveIntegerField(default=0, verbose_name='Porcentagem')),
                ('proximos_passos', models.TextField(blank=True, verbose_name='Próximos Passos')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='core.demanda')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.auxiliares.upload_anexo_path)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_set', to='core.demanda')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Todos os Anexos',
            },
        ),
        migrations.CreateModel(
            name='ResultadosEsperados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Resultados Esperados',
            },
        ),
        migrations.CreateModel(
            name='Riscos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Riscos',
            },
        ),
        migrations.AddField(
            model_name='demanda',
            name='resultados_esperados',
            field=models.ManyToManyField(blank=True, to='core.resultadosesperados', verbose_name='Resultados Esperados'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscos', verbose_name='Riscos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema', verbose_name='Tema'),
        ),
        migrations.CreateModel(
            name='Rotulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor_hex', models.CharField(default='#6c757d', help_text='Cor em Hexadecimal (ex: #007bff)', max_length=7)),
            ],
            options={
                'verbose_name': 'Rótulo',
                'verbose_name_plural': 'Rótulos',
            },
        ),
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Demanda'},
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='dependencias_externas',
            field=models.TextField(blank=True, verbose_name='Dependências Externas'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='proximos_passos',
            field=models.TextField(blank=True, verbose_name='Próximos Passos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='resultados_esperados',
            field=models.ManyToManyField(blank=True, to='core.resultadosesperados', verbose_name='Resultados Esperados'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao', verbose_name='Bucket'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='rotulos',
            field=models.ManyToManyField(blank=True, related_name='demandas', to='core.rotulos', verbose_name='Rótulos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='solicitantes',
            field=models.ManyToManyField(blank=True, related_name='demandas_solicitadas', to='core.contato', verbose_name='Solicitantes'),
        ),
        migrations.CreateModel(
            name='HistoricalDemanda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_prazo', models.DateField(blank=True, null=True, verbose_name='Data de Prazo')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.demanda', verbose_name='Demanda Pai')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('situacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.situacao', verbose_name='Bucket')),
                ('tema', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tema')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tipoatividade')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('dependencias_externas', models.TextField(blank=True, verbose_name='Dependências Externas')),
                ('objetivo_geral', models.TextField(blank=True, verbose_name='Objetivo Geral')),
                ('porcentagem_concluida', models.PositiveIntegerField(default=0, verbose_name='Porcentagem')),
                ('proximos_passos', models.TextField(blank=True, verbose_name='Próximos Passos')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Tarefa')),
                ('pendencia', models.TextField(blank=True, verbose_name='Descrição da Pendência')),
                ('pendencia_data', models.DateField(blank=True, null=True, verbose_name='Data da Pendência')),
                ('responsabilidade_pendencia', models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10, verbose_name='Responsáveis por concluir a pendência')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.demanda')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Pendência Resolvida')),
                ('pendencia_resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução da Pendência')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTarefas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Tarefa')),
                ('pendencia', models.TextField(blank=True, verbose_name='Descrição da Pendência')),
                ('pendencia_data', models.DateField(blank=True, null=True, verbose_name='Data da Pendência')),
                ('pendencia_resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução da Pendência')),
                ('responsabilidade_pendencia', models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10, verbose_name='Responsáveis por concluir a pendência')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Pendência Resolvida')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('demanda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.demanda')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tarefa',
                'verbose_name_plural': 'historical Tarefas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
