# Generated by Django 6.0 on 2025-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contato_demanda_descricao_demanda_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
