# Generated by Django 6.0 on 2025-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicaldemanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='padrao',
            field=models.BooleanField(default=False, help_text='Marcar como situação padrão para novas demandas'),
        ),
    ]
