# Generated by Django 6.0 on 2025-12-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_situacao_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='pendente',
            field=models.BooleanField(default=False, help_text="Marcar como situação que representa 'pendente'"),
        ),
    ]
