# Generated by Django 6.0 on 2025-12-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_situacao_pendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='anexos'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='anexos',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
