# Generated by Django 6.0 on 2025-12-29 23:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documento_remove_demanda_anexos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.AlterModelOptions(
            name='anexodemanda',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Todos os Anexos (Tabela Geral)'},
        ),
        migrations.AddField(
            model_name='demanda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='nivel',
            field=models.CharField(choices=[('Projeto', 'Projeto'), ('Atividade', 'Atividade'), ('Sub-item', 'Sub-item')], default='Atividade', max_length=20),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação Interna'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subitens', to='core.demanda'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='solicitantes',
            field=models.ManyToManyField(blank=True, related_name='demandas_solicitadas', to='core.contato'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoatividade'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='nivel',
            field=models.CharField(choices=[('Projeto', 'Projeto'), ('Atividade', 'Atividade'), ('Sub-item', 'Sub-item')], default='Atividade', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação Interna'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.demanda'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='cor_hex',
            field=models.CharField(default='#6c757d', help_text='Cor Hexadecimal (ex: #d9534f)', max_length=7),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalPendencia',
        ),
    ]
