# Generated by Django 6.0 on 2025-12-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pendencia_resolvido_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'Bucket', 'verbose_name_plural': 'Buckets'},
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='historicaldemanda',
            name='nivel',
        ),
    ]
