# Generated by Django 6.0 on 2026-01-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_situacao_options_remove_demanda_nivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosEsperados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Riscos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='demanda',
            name='dependencias_externas',
            field=models.TextField(blank=True, verbose_name='Dependencias Externas'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='porcentagem_concluida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='proximos_passos',
            field=models.TextField(blank=True, verbose_name='Próximos Passos'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='dependencias_externas',
            field=models.TextField(blank=True, verbose_name='Dependencias Externas'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='porcentagem_concluida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='proximos_passos',
            field=models.TextField(blank=True, verbose_name='Próximos Passos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='resultados_esperados',
            field=models.ManyToManyField(blank=True, to='core.resultadosesperados'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscos'),
        ),
    ]
