# Generated by Django 6.0 on 2026-01-06 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resultadosesperados_riscos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='porcentagem_concluida',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentagem'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='resultados_esperados',
            field=models.ManyToManyField(blank=True, to='core.resultadosesperados', verbose_name='Resultados Esperados'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscos', verbose_name='Riscos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='criado_em',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='porcentagem_concluida',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentagem'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='tema',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tema', verbose_name='Tema'),
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('pendencia', models.TextField(blank=True, verbose_name='Pendência')),
                ('pendencia_data', models.DateField(blank=True, null=True)),
                ('responsabilidade_pendencia', models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10)),
                ('concluida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.demanda')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
