# Generated by Django 6.0 on 2026-01-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_demanda_atualizado_em_alter_demanda_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='titulo',
            new_name='nome',
        ),
    ]
