# Generated by Django 6.0 on 2026-01-06 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_titulo_tarefas_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor_hex', models.CharField(default='#6c757d', help_text='Cor em Hexadecimal (ex: #007bff)', max_length=7)),
            ],
            options={
                'verbose_name': 'Rótulo',
                'verbose_name_plural': 'Rótulos',
            },
        ),
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Demanda'},
        ),
        migrations.AlterModelOptions(
            name='historicaldemanda',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Demanda', 'verbose_name_plural': 'historical Demandas'},
        ),
        migrations.AlterModelOptions(
            name='resultadosesperados',
            options={'verbose_name_plural': 'Resultados Esperados'},
        ),
        migrations.AlterModelOptions(
            name='riscos',
            options={'verbose_name_plural': 'Riscos'},
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='dependencias_externas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='objetivo_geral',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='proximos_passos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='resultados_esperados',
            field=models.ManyToManyField(blank=True, to='core.resultadosesperados'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='dependencias_externas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='objetivo_geral',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='proximos_passos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='situacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='tema',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tema'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='cor_hex',
            field=models.CharField(default='#6c757d', help_text='Ex: #d9534f', max_length=7),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='padrao',
            field=models.BooleanField(default=False, help_text='Bucket padrão para novas demandas', verbose_name='Padrão'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='pendente',
            field=models.BooleanField(default=False, help_text="Representa estado 'pendente'"),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='proximas_situacoes',
            field=models.ManyToManyField(blank=True, to='core.situacao', verbose_name='Buckets seguintes'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='pendencia',
            field=models.TextField(blank=True, verbose_name='Descrição da Pendência'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoatividade',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='rotulos',
            field=models.ManyToManyField(blank=True, related_name='demandas', to='core.rotulos', verbose_name='Rótulos'),
        ),
    ]
