# Generated by Django 6.0 on 2026-01-07 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rotulos_alter_demanda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldemanda',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='dependencias_externas',
            field=models.TextField(blank=True, verbose_name='Dependências Externas'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='proximos_passos',
            field=models.TextField(blank=True, verbose_name='Próximos Passos'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='resultados_esperados',
            field=models.ManyToManyField(blank=True, to='core.resultadosesperados', verbose_name='Resultados Esperados'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='solicitantes',
            field=models.ManyToManyField(blank=True, related_name='demandas_solicitadas', to='core.contato', verbose_name='Solicitantes'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='dependencias_externas',
            field=models.TextField(blank=True, verbose_name='Dependências Externas'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='proximos_passos',
            field=models.TextField(blank=True, verbose_name='Próximos Passos'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='situacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.situacao', verbose_name='Situação'),
        ),
    ]
