# Generated by Django 6.0 on 2026-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_historicaldemanda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
