# Generated by Django 6.0 on 2026-01-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tarefas_concluido_em_alter_tarefas_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='resolvida',
            field=models.BooleanField(default=False, verbose_name='Pendência Resolvida'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao', verbose_name='Bucket'),
        ),
        migrations.AlterField(
            model_name='historicaldemanda',
            name='situacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.situacao', verbose_name='Bucket'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='Concluída'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='responsabilidade_pendencia',
            field=models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10, verbose_name='Responsáveis por concluir a pendência'),
        ),
    ]
