# Generated by Django 6.0 on 2026-01-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tarefas_resolvida_alter_demanda_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='pendencia_resolvida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução da Pendência'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='pendencia_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Pendência'),
        ),
    ]
