# Generated by Django 6.0 on 2026-01-08 13:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tarefas_pendencia_resolvida_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTarefas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Tarefa')),
                ('pendencia', models.TextField(blank=True, verbose_name='Descrição da Pendência')),
                ('pendencia_data', models.DateField(blank=True, null=True, verbose_name='Data da Pendência')),
                ('pendencia_resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução da Pendência')),
                ('responsabilidade_pendencia', models.CharField(blank=True, choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10, verbose_name='Responsáveis por concluir a pendência')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Pendência Resolvida')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('demanda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.demanda')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tarefa',
                'verbose_name_plural': 'historical Tarefas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
