# Generated by Django 6.0 on 2026-01-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_0024_historicaltarefas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.AddField(
            model_name='historicaltarefas',
            name='horas_estimadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas Estimadas'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='horas_estimadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas Estimadas'),
        ),
    ]
