# Generated by Django 6.0 on 2026-01-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_demanda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demanda',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Demanda'},
        ),
    ]
