# Generated by Django 6.0 on 2026-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_demanda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='fechado',
            field=models.BooleanField(default=False, help_text='Indica se é um estado final (fechado)'),
        ),
    ]
