# Generated by Django 6.0 on 2026-01-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_situacao_fechado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltarefas',
            name='pendencia_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Pendência'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='pendencia_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Pendência'),
        ),
    ]
