# Generated by Django 6.0 on 2026-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_historicaltarefas_pendencia_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltarefas',
            name='nome',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='nome',
            field=models.TextField(max_length=255),
        ),
    ]
