# Generated by Django 6.0 on 2026-01-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_historicaltarefas_nome_alter_tarefas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='conclusao',
            field=models.TextField(blank=True, verbose_name='Conclusão'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='conclusao',
            field=models.TextField(blank=True, verbose_name='Conclusão'),
        ),
    ]
