# Generated by Django 6.0 on 2026-01-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_demanda_conclusao_historicaldemanda_conclusao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['demanda', 'prioridade'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='historicaltarefas',
            name='prioridade',
            field=models.PositiveIntegerField(default=0, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='prioridade',
            field=models.PositiveIntegerField(default=0, verbose_name='Prioridade'),
        ),
    ]
