# Generated by Django 6.0 on 2026-01-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_tarefas_options_historicaltarefas_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'ordering': ['prioridade'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
