# Generated by Django 6.0 on 2026-01-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_tarefas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltarefas',
            name='nome',
            field=models.TextField(max_length=255, verbose_name='Nome da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='nome',
            field=models.TextField(max_length=255, verbose_name='Nome da Tarefa'),
        ),
    ]
