# Generated by Django 6.0 on 2026-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_historicaltarefas_nome_alter_tarefas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='pmo',
            field=models.BooleanField(default=False, verbose_name='Tela PMO'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='pmo',
            field=models.BooleanField(default=False, verbose_name='Tela PMO'),
        ),
    ]
