# Generated by Django 6.0 on 2026-01-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_demanda_pmo_historicaldemanda_pmo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Frente')),
            ],
        ),
        migrations.AddField(
            model_name='demanda',
            name='frente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frente_demanda', to='core.frente', verbose_name='Frente'),
        ),
        migrations.AddField(
            model_name='historicaldemanda',
            name='frente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.frente', verbose_name='Frente'),
        ),
    ]
