# Generated by Django 6.0 on 2026-01-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_frente_demanda_frente_historicaldemanda_frente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldemanda',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='frente',
        ),
        migrations.DeleteModel(
            name='Frente',
        ),
    ]
