# Generated by Django 6.0 on 2026-01-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_historicaldemanda_frente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='temas',
            field=models.ManyToManyField(related_name='temas', to='core.tema'),
        ),
    ]
