# Generated by Django 6.0 on 2026-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_demanda_temas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='cor_hex',
            field=models.CharField(default='#6c757d', help_text='Ex: #d9534f', max_length=7),
        ),
    ]
