# Generated by Django 6.0 on 2026-01-27 20:30

from django.db import migrations

def copiar_dados_fk_para_m2m(apps, schema_editor):
    # Pegamos o modelo de forma dinâmica para evitar erros de importação
    Demanda = apps.get_model('core', 'Demanda')
    
    for objeto in Demanda.objects.all():
        # Se existir um valor no campo antigo (FK)
        if objeto.tema_id: 
            # Adicionamos esse ID ao novo campo (M2M)
            objeto.temas.add(objeto.tema_id)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_tema_cor_hex'),
    ]

    operations = [
        migrations.RunPython(copiar_dados_fk_para_m2m),
    ]
