# Generated by Django 6.0 on 2026-01-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20260127_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='temas',
        ),
    ]
