# Generated by Django 6.0 on 2026-01-29 20:24

from django.db import migrations


def atualizar_flag_pmo(apps, schema_editor):
    Demanda = apps.get_model("core", "Demanda")
    Tema = apps.get_model("core", "Tema")

    tema_cliente = Tema.objects.filter(nome="Cliente").first()

    if tema_cliente:
            
        demandas_para_atualizar = Demanda.objects.filter(tema_id=tema_cliente.id).update(pmo=True)
        
        tema_cliente.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_remove_demanda_temas"),
    ]

    operations = [
        migrations.RunPython(atualizar_flag_pmo, reverse_code=migrations.RunPython.noop),
    ]
