# Generated by Django 6.0 on 2026-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20260129_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='execucao',
            field=models.BooleanField(default=False, verbose_name='Indica qual o bucket de execução'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='fechado',
            field=models.BooleanField(default=False, help_text='Indica se é um o bucket final (fechado)', verbose_name='Fechado'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='pendente',
            field=models.BooleanField(default=False, help_text="Representa o bucket 'pendente'"),
        ),
    ]
