# Generated by Django 6.0 on 2026-03-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCPLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido_logicamente', models.BooleanField(default=False, verbose_name='Excluído')),
                ('marcado_para_exclusao_fisica', models.BooleanField(default=False, verbose_name='Apagar')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Localização GCP',
                'verbose_name_plural': 'Localizações GCP',
            },
        ),
        migrations.CreateModel(
            name='GCPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido_logicamente', models.BooleanField(default=False, verbose_name='Excluído')),
                ('marcado_para_exclusao_fisica', models.BooleanField(default=False, verbose_name='Apagar')),
                ('project_id', models.CharField(max_length=128, unique=True, verbose_name='ID do Projeto GCP')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Nome de Exibição')),
            ],
            options={
                'verbose_name': 'Projeto GCP',
                'verbose_name_plural': 'Projetos GCP',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido_logicamente', models.BooleanField(default=False, verbose_name='Excluído')),
                ('marcado_para_exclusao_fisica', models.BooleanField(default=False, verbose_name='Apagar')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Projeto de Desenvolvimento',
                'verbose_name_plural': 'Projetos de Desenvolvimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GCPAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido_logicamente', models.BooleanField(default=False, verbose_name='Excluído')),
                ('marcado_para_exclusao_fisica', models.BooleanField(default=False, verbose_name='Apagar')),
                ('name', models.CharField(max_length=256, verbose_name='Nome (Dataset/Bucket)')),
                ('asset_type', models.CharField(choices=[('BQ', 'BigQuery Dataset'), ('GCS', 'Cloud Storage Bucket')], max_length=10, verbose_name='Tipo')),
                ('uri', models.CharField(max_length=512, unique=True, verbose_name='URI')),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineage.gcplocation', verbose_name='Localização')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='lineage.gcpproject', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Ativo GCP',
                'verbose_name_plural': 'Ativos GCP',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GCPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido_logicamente', models.BooleanField(default=False, verbose_name='Excluído')),
                ('marcado_para_exclusao_fisica', models.BooleanField(default=False, verbose_name='Apagar')),
                ('table_name', models.CharField(max_length=256, verbose_name='Nome da Tabela')),
                ('table_type', models.CharField(blank=True, choices=[('TABLE', 'Tabela Nativa'), ('EXTERNAL', 'Tabela Externa'), ('VIEW', 'View'), ('MATERIALIZED_VIEW', 'View Materializada'), ('BLOB', 'Blob/Folder GCS')], max_length=50, verbose_name='Tipo')),
                ('is_partitioned', models.BooleanField(default=False, verbose_name='Particionada?')),
                ('partition_columns', models.JSONField(blank=True, default=list, verbose_name='Colunas de Partição')),
                ('partitions_found', models.JSONField(blank=True, default=list, verbose_name='Partições Detectadas')),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('metadata_raw', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='lineage.gcpasset', verbose_name='Ativo')),
                ('projetos', models.ManyToManyField(blank=True, related_name='tabelas', to='lineage.projetodesenvolvimento')),
            ],
            options={
                'verbose_name': 'Tabela/Blob',
                'verbose_name_plural': 'Tabelas/Blobs',
                'unique_together': {('asset', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='GCPETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido_logicamente', models.BooleanField(default=False, verbose_name='Excluído')),
                ('marcado_para_exclusao_fisica', models.BooleanField(default=False, verbose_name='Apagar')),
                ('nome_processo', models.CharField(blank=True, max_length=512, unique=True, verbose_name='Processo')),
                ('tipos_etl', models.JSONField(default=list, verbose_name='Tipos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etls_entrada', to='lineage.gcptable', verbose_name='Destino')),
                ('fontes', models.ManyToManyField(blank=True, related_name='etls_saida', to='lineage.gcptable', verbose_name='Fontes')),
            ],
            options={
                'verbose_name': 'Processo ETL',
                'verbose_name_plural': 'Processos ETL',
            },
        ),
    ]
