# Generated by Django 6.0 on 2026-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpasset',
            name='query',
            field=models.TextField(blank=True, verbose_name='Query'),
        ),
    ]
