# Generated by Django 6.0 on 2026-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCPAsset',
            fields=[
                ('uri', models.CharField(max_length=512, primary_key=True, serialize=False, unique=True, verbose_name='URI (ID Único)')),
                ('asset_type', models.CharField(choices=[('BQ', 'BigQuery'), ('GCS', 'Cloud Storage')], max_length=10, verbose_name='Tipo de Ativo')),
                ('project_id', models.CharField(max_length=128, verbose_name='ID do Projeto')),
                ('location', models.CharField(blank=True, max_length=128, null=True, verbose_name='Localização')),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('labels', models.JSONField(blank=True, default=dict, verbose_name='Rótulos (Labels)')),
                ('access_config', models.JSONField(blank=True, default=list, verbose_name='Configuração de Acesso (IAM)')),
                ('lifecycle_rules', models.JSONField(blank=True, default=list, verbose_name='Regras de Ciclo de Vida')),
                ('policies', models.JSONField(blank=True, default=dict, verbose_name='Políticas')),
                ('creation_time', models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização no GCP')),
                ('last_imported_at', models.DateTimeField(auto_now=True, verbose_name='Data da Última Importação')),
            ],
            options={
                'verbose_name': 'Ativo GCP',
                'verbose_name_plural': 'Ativos GCP',
                'ordering': ['project_id', 'name'],
            },
        ),
    ]
