# Generated by Django 6.0 on 2026-03-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0002_gcpasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Projeto de Desenvolvimento',
                'verbose_name_plural': 'Projetos de Desenvolvimento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='gcpasset',
            name='asset_type',
            field=models.CharField(choices=[('BQ', 'BigQuery Dataset'), ('GCS', 'Cloud Storage Bucket')], max_length=10, verbose_name='Tipo de Ativo'),
        ),
        migrations.AlterField(
            model_name='gcpasset',
            name='project_id',
            field=models.CharField(max_length=128, verbose_name='ID do Projeto GCP'),
        ),
        migrations.CreateModel(
            name='GCPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=256, verbose_name='Nome da Tabela/Blob')),
                ('table_schema', models.CharField(blank=True, max_length=256, verbose_name='Schema/Dataset')),
                ('table_catalog', models.CharField(blank=True, max_length=256, verbose_name='Catálogo/Projeto')),
                ('table_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('ddl', models.TextField(blank=True, verbose_name='DDL / Definição')),
                ('is_insertable_into', models.CharField(blank=True, max_length=10)),
                ('is_typed', models.CharField(blank=True, max_length=10)),
                ('creation_time', models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação')),
                ('metadata_raw', models.JSONField(blank=True, default=dict, verbose_name='Metadados Brutos')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='lineage.gcpasset', verbose_name='Ativo Pai')),
                ('projetos', models.ManyToManyField(blank=True, related_name='tabelas', to='lineage.projetodesenvolvimento', verbose_name='Projetos de Desenvolvimento')),
            ],
            options={
                'verbose_name': 'Tabela/Blob',
                'verbose_name_plural': 'Tabelas/Blobs',
                'ordering': ['table_name'],
                'unique_together': {('asset', 'table_name')},
            },
        ),
    ]
