# Generated by Django 6.0 on 2026-03-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0003_projetodesenvolvimento_alter_gcpasset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gcptable',
            unique_together={('table_catalog', 'table_schema', 'table_name')},
        ),
        migrations.AlterField(
            model_name='gcpasset',
            name='location',
            field=models.CharField(blank=True, choices=[('US', 'US (Multi-region)'), ('EU', 'EU (Multi-region)'), ('southamerica-east1', 'São Paulo (southamerica-east1)'), ('southamerica-west1', 'Santiago (southamerica-west1)'), ('us-central1', 'Iowa (us-central1)'), ('us-east1', 'South Carolina (us-east1)'), ('us-east4', 'Northern Virginia (us-east4)'), ('us-west1', 'Oregon (us-west1)'), ('asia-east1', 'Taiwan (asia-east1)'), ('europe-west1', 'Belgium (europe-west1)'), ('europe-west3', 'Frankfurt (europe-west3)')], max_length=128, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='gcptable',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='lineage.gcpasset', verbose_name='Ativo Pai'),
        ),
        migrations.AlterField(
            model_name='gcptable',
            name='is_insertable_into',
            field=models.BooleanField(default=False, verbose_name='Inserível?'),
        ),
        migrations.AlterField(
            model_name='gcptable',
            name='is_typed',
            field=models.BooleanField(default=False, verbose_name='Tipada?'),
        ),
        migrations.AlterField(
            model_name='gcptable',
            name='table_type',
            field=models.CharField(blank=True, choices=[('BASE TABLE', 'Base Table'), ('VIEW', 'View'), ('EXTERNAL', 'External Table'), ('MATERIALIZED VIEW', 'Materialized View'), ('BLOB', 'Storage Blob/File')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='gcpasset',
            unique_together={('project_id', 'name')},
        ),
    ]
