# Generated by Django 6.0 on 2026-03-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0004_alter_gcptable_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código da Região (ex: us-central1)')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Amigável')),
            ],
            options={
                'verbose_name': 'Localização GCP',
                'verbose_name_plural': 'Localizações GCP',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='gcpasset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineage.gcplocation', verbose_name='Localização'),
        ),
    ]
