# Generated by Django 6.0 on 2026-03-30 22:57

import django.db.models.deletion
import gcp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0040_remove_demanda_temas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Solicitar deleção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Localização GCP',
                'verbose_name_plural': 'Localizações GCP',
            },
        ),
        migrations.CreateModel(
            name='GCPDevProject',
            fields=[
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Solicitar deleção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Nome do Projeto de Desenvolvimento')),
                ('description', models.TextField(verbose_name='Descrição do projeto')),
                ('responsable_users', models.ManyToManyField(related_name='dev_projects_responsable_users', to='core.contato', verbose_name='Time da área de negócios')),
            ],
            options={
                'verbose_name': 'Projeto de desenvolvimento',
                'verbose_name_plural': 'Projetos de desenvolvimento',
            },
        ),
        migrations.CreateModel(
            name='GCPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Solicitar deleção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('project_id', models.CharField(max_length=256, unique=True, verbose_name='Id do projeto')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Nome do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto GCP',
                'verbose_name_plural': 'Projetos GCP',
                'unique_together': {('project_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GCPAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Solicitar deleção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=256, verbose_name='Nome (Dataset/Bucket)')),
                ('asset_types', models.CharField(choices=[('BQ', 'BigQuery Dataset'), ('GCS', 'Cloud Storage Bucket')], max_length=10, verbose_name='Tipo de Ativo')),
                ('uri', models.CharField(max_length=512, unique=True, verbose_name='URI')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.gcplocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gcp.gcpproject', to_field='name')),
            ],
            options={
                'verbose_name': 'Ativo GCP',
                'verbose_name_plural': 'Ativos GCP',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GCPTableBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Solicitar deleção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('table_name', models.CharField(help_text='Nome da tabela (Este campo é chave única composta junto com projeto e dataset/bucket)', max_length=256, verbose_name='Nome da Tabela')),
                ('table_type', models.CharField(blank=True, choices=[('TABLE', 'Tabela Nativa'), ('EXTERNAL', 'Tabela Externa'), ('VIEW', 'View'), ('MATERIALIZED_VIEW', 'View Materializada'), ('BLOB', 'Blob/Folder GCS')], help_text='Indica qual o tipo da fonte', max_length=50, verbose_name='Tipo')),
                ('is_partitioned', models.BooleanField(default=False, help_text='Indica se este item tem particionamento', verbose_name='Particionada?')),
                ('partitions_fields', models.CharField(blank=True, help_text='Indica os campos que compõe a partição', max_length=256, null=True, verbose_name='Colunas particionadas')),
                ('partitions_found', models.JSONField(blank=True, default=list, help_text='Partições encontradas através de importação (JSON)', null=True, verbose_name='Partições Detectadas')),
                ('ddl', models.TextField(blank=True, help_text='Código DDL de Tabelas do BigQuery', null=True, verbose_name='DDL da tabela')),
                ('metadata_raw', models.JSONField(blank=True, default=dict, help_text='RAW da Importação do Item', null=True)),
                ('creation_time', models.DateField(blank=True, help_text='Data de criação do item no Google Cloud', null=True, verbose_name='Data de criação')),
                ('asset', models.ForeignKey(help_text='Nome do Dataset/Bucket em que está a tabela ou blob.', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='gcp.gcpasset', verbose_name='Ativo')),
                ('project_dev', models.ManyToManyField(blank=True, help_text='Projetos que utilizam está fonte', related_name='tabelas', to='gcp.gcpdevproject', verbose_name='Projetos de desenvolvimento')),
            ],
            options={
                'verbose_name': 'Tabela/Blob',
                'verbose_name_plural': 'Tabelas/Blobs',
                'unique_together': {('asset', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='GCPETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Solicitar deleção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(blank=True, max_length=512, unique=True, verbose_name='Processo')),
                ('etl_types', models.JSONField(default=list, verbose_name='Tipos')),
                ('cronjob', models.CharField(blank=True, help_text='Insira uma expressão cron (ex: 0 5 * * 1)', max_length=20, null=True, validators=[gcp.models.validate_cron], verbose_name='Agendamento (Cron)')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('destin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etls_entrada', to='gcp.gcptableblob', verbose_name='Tabela de destino')),
                ('source', models.ManyToManyField(blank=True, related_name='etls_saida', to='gcp.gcptableblob', verbose_name="Tabela's/Blob's Fontes")),
            ],
            options={
                'verbose_name': 'Processo ETL',
                'verbose_name_plural': 'Processos ETL',
            },
        ),
    ]
