# Generated by Django 6.0 on 2026-03-30 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0040_remove_demanda_temas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Apagar')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Localização GCP',
                'verbose_name_plural': 'Localizações GCP',
            },
        ),
        migrations.CreateModel(
            name='GCPDevProjects',
            fields=[
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Apagar')),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Nome do Projeto de Desenvolvimento')),
                ('description', models.TextField(verbose_name='Descrição do projeto')),
                ('responsable_users', models.ManyToManyField(related_name='dev_projects_responsable_users', to='core.contato', verbose_name='Time da área de negócios')),
            ],
            options={
                'verbose_name': 'Projeto de desenvolvimento',
                'verbose_name_plural': 'Projetos de desenvolvimento',
            },
        ),
        migrations.CreateModel(
            name='GCPProject',
            fields=[
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Apagar')),
                ('project_id', models.CharField(max_length=256, verbose_name='Id do projeto')),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Nome do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'unique_together': {('project_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GCPAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_in', models.DateTimeField(auto_created=True, verbose_name='Importado em')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Apagar')),
                ('name', models.CharField(max_length=256, verbose_name='Nome (Dataset/Bucket)')),
                ('asset_types', models.CharField(choices=[('BQ', 'BigQuery Dataset'), ('GCS', 'Cloud Storage Bucket')], max_length=10, verbose_name='Tipo de Ativo')),
                ('uri', models.CharField(max_length=512, unique=True, verbose_name='URI')),
                ('last_imported', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcp.gcplocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gcp.gcpproject')),
            ],
            options={
                'verbose_name': 'Ativo GCP',
                'verbose_name_plural': 'Ativos GCP',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GCPTableBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_in', models.DateTimeField(auto_created=True, verbose_name='Importado em')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluído')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Apagar')),
                ('table_name', models.CharField(max_length=256, verbose_name='Nome da Tabela')),
                ('table_type', models.CharField(blank=True, choices=[('TABLE', 'Tabela Nativa'), ('EXTERNAL', 'Tabela Externa'), ('VIEW', 'View'), ('MATERIALIZED_VIEW', 'View Materializada'), ('BLOB', 'Blob/Folder GCS')], max_length=50, verbose_name='Tipo')),
                ('is_partitioned', models.BooleanField(default=False, verbose_name='Particionada?')),
                ('partitions_found', models.JSONField(blank=True, default=list, verbose_name='Partições Detectadas')),
                ('ddl', models.TextField(blank=True, null=True, verbose_name='DDL da tabela')),
                ('metadata_raw', models.JSONField(blank=True, default=dict)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('last_imported', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='gcp.gcpasset', verbose_name='Ativo')),
                ('project_dev', models.ManyToManyField(blank=True, related_name='tabelas', to='gcp.gcpdevprojects', verbose_name='Projeto de desenvolvimento')),
            ],
            options={
                'verbose_name': 'Tabela/Blob',
                'verbose_name_plural': 'Tabelas/Blobs',
                'unique_together': {('asset', 'table_name')},
            },
        ),
    ]
