# Generated by Django 6.0 on 2026-03-30 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gcpasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gcp.gcpproject', to_field='name'),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='project_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='Id do projeto'),
        ),
    ]
