# Generated by Django 6.0 on 2026-03-30 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0002_gcpproject_id_alter_gcpasset_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcptableblob',
            old_name='import_in',
            new_name='imported_in',
        ),
        migrations.AddField(
            model_name='gcpdevprojects',
            name='imported_in',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2026, 3, 30, 3, 53, 44, 510039, tzinfo=datetime.timezone.utc), verbose_name='Importado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcpdevprojects',
            name='last_imported',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='gcplocation',
            name='imported_in',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2026, 3, 30, 3, 53, 52, 251960, tzinfo=datetime.timezone.utc), verbose_name='Importado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcplocation',
            name='last_imported',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='gcpproject',
            name='imported_in',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2026, 3, 30, 3, 54, 0, 871561, tzinfo=datetime.timezone.utc), verbose_name='Importado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcpproject',
            name='last_imported',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
    ]
