# Generated by Django 6.0 on 2026-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0003_rename_import_in_gcptableblob_imported_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcpasset',
            name='imported_in',
        ),
        migrations.RemoveField(
            model_name='gcpasset',
            name='last_imported',
        ),
        migrations.RemoveField(
            model_name='gcpdevprojects',
            name='imported_in',
        ),
        migrations.RemoveField(
            model_name='gcpdevprojects',
            name='last_imported',
        ),
        migrations.RemoveField(
            model_name='gcplocation',
            name='imported_in',
        ),
        migrations.RemoveField(
            model_name='gcplocation',
            name='last_imported',
        ),
        migrations.RemoveField(
            model_name='gcplocation',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='gcpproject',
            name='imported_in',
        ),
        migrations.RemoveField(
            model_name='gcpproject',
            name='last_imported',
        ),
        migrations.RemoveField(
            model_name='gcptableblob',
            name='imported_in',
        ),
        migrations.RemoveField(
            model_name='gcptableblob',
            name='last_imported',
        ),
        migrations.AddField(
            model_name='gcplocation',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
