# Generated by Django 6.0 on 2026-03-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0004_remove_gcpasset_imported_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpasset',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='gcpdevprojects',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='gcplocation',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='gcpproject',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='gcptableblob',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
