# Generated by Django 6.0 on 2026-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0006_gcpasset_update_gcpdevprojects_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcptableblob',
            name='partitions_fields',
            field=models.CharField(blank=True, max_length=256, verbose_name='Colunas particionadas'),
        ),
    ]
