# Generated by Django 6.0 on 2026-03-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0008_alter_gcpasset_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpasset',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluir'),
        ),
        migrations.AlterField(
            model_name='gcpdevprojects',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluir'),
        ),
        migrations.AlterField(
            model_name='gcplocation',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluir'),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluir'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='gcp.gcpasset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluir'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='project_dev',
            field=models.ManyToManyField(blank=True, related_name='tabelas', to='gcp.gcpdevprojects'),
        ),
        migrations.CreateModel(
            name='GCPETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_exclusion', models.BooleanField(default=False, verbose_name='Excluir')),
                ('to_make_exclude', models.BooleanField(default=False, verbose_name='Apagar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(blank=True, max_length=512, unique=True, verbose_name='Processo')),
                ('etl_types', models.JSONField(default=list, verbose_name='Tipos')),
                ('destin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etls_entrada', to='gcp.gcptableblob')),
                ('source', models.ManyToManyField(blank=True, related_name='etls_saida', to='gcp.gcptableblob', verbose_name='Fontes')),
            ],
            options={
                'verbose_name': 'Processo ETL',
                'verbose_name_plural': 'Processos ETL',
            },
        ),
    ]
