# Generated by Django 6.0 on 2026-03-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_demanda_temas'),
        ('gcp', '0009_alter_gcpasset_logical_exclusion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GCPDevProjects',
            new_name='GCPDevProject',
        ),
        migrations.AlterModelOptions(
            name='gcpproject',
            options={'verbose_name': 'Projeto GCP', 'verbose_name_plural': 'Projetos GCP'},
        ),
    ]
