# Generated by Django 6.0 on 2026-03-30 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0010_rename_gcpdevprojects_gcpdevproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpproject',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='gcp.gcplocation'),
        ),
    ]
