# Generated by Django 6.0 on 2026-03-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0011_gcpproject_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpasset',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='gcpasset',
            name='to_make_exclude',
            field=models.BooleanField(default=False, verbose_name='Solicitar deleção'),
        ),
        migrations.AlterField(
            model_name='gcpdevproject',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='gcpdevproject',
            name='to_make_exclude',
            field=models.BooleanField(default=False, verbose_name='Solicitar deleção'),
        ),
        migrations.AlterField(
            model_name='gcpetl',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='gcpetl',
            name='to_make_exclude',
            field=models.BooleanField(default=False, verbose_name='Solicitar deleção'),
        ),
        migrations.AlterField(
            model_name='gcplocation',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='gcplocation',
            name='to_make_exclude',
            field=models.BooleanField(default=False, verbose_name='Solicitar deleção'),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='to_make_exclude',
            field=models.BooleanField(default=False, verbose_name='Solicitar deleção'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='asset',
            field=models.ForeignKey(help_text='Nome do Dataset/Bucket em que está a tabela ou blob.', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='gcp.gcpasset', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='creation_time',
            field=models.DateField(blank=True, help_text='Data de criação do item no Google Cloud', null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='is_partitioned',
            field=models.BooleanField(default=False, help_text='Indica se este item tem particionamento', verbose_name='Particionada?'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='logical_exclusion',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='partitions_fields',
            field=models.CharField(blank=True, help_text='Indica os campos que compõe a partição', max_length=256, verbose_name='Colunas particionadas'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='partitions_found',
            field=models.JSONField(blank=True, default=list, help_text='Partições encontradas através de importação (JSON)', verbose_name='Partições Detectadas'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='project_dev',
            field=models.ManyToManyField(blank=True, help_text='Projetos que utilizam está fonte', related_name='tabelas', to='gcp.gcpdevproject', verbose_name='Projetos de desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='table_name',
            field=models.CharField(help_text='Nome da tabela (Este campo é chave única composta junto com projeto e dataset/bucket)', max_length=256, verbose_name='Nome da Tabela'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='table_type',
            field=models.CharField(blank=True, choices=[('TABLE', 'Tabela Nativa'), ('EXTERNAL', 'Tabela Externa'), ('VIEW', 'View'), ('MATERIALIZED_VIEW', 'View Materializada'), ('BLOB', 'Blob/Folder GCS')], help_text='Indica qual o tipo da fonte', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='to_make_exclude',
            field=models.BooleanField(default=False, verbose_name='Solicitar deleção'),
        ),
    ]
