# Generated by Django 6.0 on 2026-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0012_alter_gcpasset_logical_exclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcptableblob',
            name='ddl',
            field=models.TextField(blank=True, help_text='Código DDL de Tabelas do BigQuery', null=True, verbose_name='DDL da tabela'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='metadata_raw',
            field=models.JSONField(blank=True, default=dict, help_text='RAW da Importação do Item'),
        ),
    ]
