# Generated by Django 6.0 on 2026-03-30 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0013_alter_gcptableblob_ddl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpetl',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 30, 18, 45, 34, 956579, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
