# Generated by Django 6.0 on 2026-03-30 19:02

import gcp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0014_gcpetl_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpetl',
            name='cronjob',
            field=models.CharField(blank=True, help_text='Insira uma expressão cron (ex: 0 5 * * 1)', max_length=9, null=True, validators=[gcp.models.validate_cron], verbose_name='Agendamento (Cron)'),
        ),
    ]
