# Generated by Django 6.0 on 2026-03-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0016_alter_gcpetl_cronjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpetl',
            name='destin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etls_entrada', to='gcp.gcptableblob', verbose_name='Tabela de destino'),
        ),
        migrations.AlterField(
            model_name='gcpetl',
            name='source',
            field=models.ManyToManyField(blank=True, related_name='etls_saida', to='gcp.gcptableblob', verbose_name="Tabela's/Blob's Fontes"),
        ),
    ]
