# Generated by Django 6.0 on 2026-03-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0017_alter_gcpetl_destin_alter_gcpetl_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcpproject',
            name='location',
        ),
    ]
