# Generated by Django 6.0 on 2026-03-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0018_remove_gcpproject_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcptableblob',
            name='metadata_raw',
            field=models.JSONField(blank=True, default=dict, help_text='RAW da Importação do Item', null=True),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='partitions_fields',
            field=models.CharField(blank=True, help_text='Indica os campos que compõe a partição', max_length=256, null=True, verbose_name='Colunas particionadas'),
        ),
        migrations.AlterField(
            model_name='gcptableblob',
            name='partitions_found',
            field=models.JSONField(blank=True, default=list, help_text='Partições encontradas através de importação (JSON)', null=True, verbose_name='Partições Detectadas'),
        ),
    ]
